import { HashMap, Key } from "./hashMap.js";

const testDing = new HashMap(0.75, 16);
testDing.set("apple", "red");
testDing.set("banana", "yellow");
testDing.set("carrot", "orange");
testDing.set("dog", "brown");
testDing.set("elephant", "gray");
testDing.set("frog", "green");
testDing.set("grape", "purple");
testDing.set("hat", "black");
testDing.set("ice cream", "white");
testDing.set("jacket", "blue");
testDing.set("kite", "pink");
testDing.set("lion", "golden");
testDing.set("lion", "blue");

console.log(testDing.get("pupi"));
console.log(testDing.has("grape"));
console.log(testDing);
console.log(testDing.remove("lion"));
console.log(testDing);
console.log(testDing.length());
console.log(testDing.clear());
console.log(testDing);

testDing.set("apple", "red");
testDing.set("banana", "yellow");
testDing.set("carrot", "orange");
testDing.set("dog", "brown");
testDing.set("elephant", "gray");
testDing.set("frog", "green");
testDing.set("grape", "purple");
testDing.set("hat", "black");
testDing.set("ice cream", "white");
testDing.set("jacket", "blue");
testDing.set("kite", "pink");
testDing.set("lion", "golden");
testDing.set("lion", "blue");
console.log(testDing.keys());
console.log(testDing.values());
console.log(testDing.entries());
testDing.set("hats", "yellow");
console.log(testDing);
console.log(testDing.clear());
console.log(testDing.length());